image: dr.rechenknecht.net/bauhelfer/container/main/rust:latest

stages:
  - build
  - test
  - filter
  - pack

variables:
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Disable running umask 000 during git clone, see https://gitlab.com/gitlab-org/gitlab-runner/-/issues/37304
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"

build:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/lcc-web-api
      - target/release/leaked-passwords-filter-tool
    expire_in: 1 week
    when: always
  needs: []

lint:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy -- -Dwarnings
    - rustup component add rustfmt
    - cargo fmt --all -- --check
  needs: []

test:small-filter:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/library/debian:stable
  stage: test
  script:
    - echo -n "test" | sha1sum > hashes
    - echo -n "test2" | sha1sum >> hashes
    - echo -n "test3" | sha1sum >> hashes
    - target/release/leaked-passwords-filter-tool ./hashes ./filter.bincode -b
  needs:
    - build

docker:bin:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/library/docker:latest
  services:
    - name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/library/docker:dind
      alias: docker
  stage: pack
  tags:
    # Use a privileged runner for building Docker container
    - privileged
  variables:
    IMAGE_TAG_ENV: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:bin-b$CI_PIPELINE_IID
    IMAGE_TAG_V1: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:bin-v1
    IMAGE_TAG_GENERAL: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:bin-latest
  needs:
    - job: build
      artifacts: true
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build
      -f "${CI_PROJECT_DIR}/Dockerfile_bin"
      -t "${IMAGE_TAG_ENV}"
      -t "${IMAGE_TAG_V1}"
      -t "${IMAGE_TAG_GENERAL}"
      --push
      .

filter:hibp:
  stage: filter
  image: mcr.microsoft.com/dotnet/sdk:8.0-noble
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet tool install --global haveibeenpwned-downloader
    - haveibeenpwned-downloader -p 128 pwnedpasswords
    - ./target/release/leaked-passwords-filter-tool pwnedpasswords.txt target/release/filter.bincode -b
  artifacts:
    paths:
      - target/release/filter.bincode
    expire_in: 1 week
    when: always

docker:api-all:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/library/docker:latest
  services:
    - name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/library/docker:dind
      alias: docker
  stage: pack
  tags:
    # Use a privileged runner for building Docker container
    - privileged
  variables:
    IMAGE_TAG_ENV: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:api-b${CI_PIPELINE_IID}-all
    IMAGE_TAG_V1: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:api-v1-all
    IMAGE_TAG_GENERAL: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:api-latest-all
  needs:
    - job: build
      artifacts: true
    - job: filter:hibp
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build
      -f "${CI_PROJECT_DIR}/Dockerfile_filter"
      -t "${IMAGE_TAG_ENV}"
      -t "${IMAGE_TAG_V1}"
      -t "${IMAGE_TAG_GENERAL}"
      --push
      .
