[workspace]
resolver = "2"
members =[
    "lcc-lib",
    "lcc-web-api",
    "leaked-passwords-filter-tool",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
