FROM debian:stable

LABEL org.opencontainers.image.authors="leo@mixxplorer.de"

COPY target/release/filter.bincode /data/filter.bincode

COPY ./target/release/leaked-passwords-filter-tool /usr/local/bin/
COPY ./target/release/lcc-web-api /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/lcc-web-api", "--filter-file", "/data/filter.bincode"]
CMD ["--bind-addr", "0.0.0.0:3000"]
