FROM rust:1

ARG REMOTE_USER=developer
ARG REMOTE_UID=992
ARG REMOTE_GID=992

RUN groupadd --gid $REMOTE_GID $REMOTE_USER \
    && useradd --uid $REMOTE_UID --gid $REMOTE_GID -m $REMOTE_USER -s /bin/bash

# Allow calling sudo in devcontainer (e.g. to install additional packages), enable if required
# RUN apt-get update && apt-get install -y sudo
# RUN echo $REMOTE_USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$REMOTE_USER

# This must be the last step as the REMOTE_UID is not set here, apparently it is not possible
# to setup users properly during container build.
USER $REMOTE_USER
