FROM rust:1

ARG REMOTE_USER
ARG REMOTE_UID
ARG REMOTE_GID

RUN groupadd --gid $REMOTE_GID $REMOTE_USER \
    && useradd --uid $REMOTE_UID --gid $REMOTE_GID -m $REMOTE_USER -s /bin/bash

# Allow calling sudo in devcontainer (e.g. to install additional packages), enable if required
# RUN apt-get update && apt-get install -y sudo
# RUN echo $REMOTE_USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$REMOTE_USER

USER $REMOTE_USER

RUN rustup component add rustfmt
RUN rustup component add clippy
RUN cargo install cargo-audit --locked --features=fix
